#
# @copyright   Copyright (C) 2023 Combodo SARL
# @license     http://opensource.org/licenses/AGPL-3.0
#
# This playbook...
#
# Input parameters:
#  - itop_class:
#  - itop_attributes:
#  - primary_key:
#  - host_attributes:
#
# Output parameters:
#  - csv_file:
#
---
- name: xxx
  hosts: all, localhost

  gather_facts: false

  vars:
    # Path to the working directories as seen from the <collector>/collectors/src/playbooks directory
    raw_directory: ../../../data/facts/raw
    csv_directory: ../../../data/facts/csv
    # Name of the output file
    itop_class: osversion
    csv_file: "{{ csv_directory }}/ansible.{{ itop_class }}.csv"
    itop_attributes:
      - os_version
      - os_family
    primary_key:
      - ansible_distribution
      - ansible_distribution_version
    host_attributes:
      - ansible_distribution
      - ansible_distribution_version

  tasks:
    - name: Create csv file
      ansible.builtin.copy:
        content: "primary_key,{{ itop_attributes | join(',') }}"
        dest: "{{ csv_file }}"

    - name: Add one line per host
      include_tasks: ./ansible.collect.line.yml
      vars:
        hostname: "{{ item }}"
      loop: "{{ play_hosts }}"
