#
# @copyright   Copyright (C) 2023 Combodo SARL
# @license     http://opensource.org/licenses/AGPL-3.0
#
# This playbook...
#
# Input parameters:
#  - itop_class: iTop class of object that is presently collected.
#  - itop_attributes: Array containing the iTop attributes that should be collected for that class.
#  - primary_key: Array containing Ansible attributes used to build the primary key
#  - host_attributes: Array of Ansible attributes to lookup in the raw file and to add to the csv output.
#
# Output parameters:
#  - csv_file: CSV file containing all object belonging to the itop_class to be synchronized
#
---
- name: Build CSV file containing all objects of a given class to be synchronized within iTop
  hosts: all, localhost

  gather_facts: false

  vars:
    # Name of the output file
    csv_file: "{{ csv_directory }}/ansible.{{ itop_class }}.csv"

  tasks:
    - name: Create csv file
      ansible.builtin.copy:
        content: "primary_key,{{ itop_attributes | join(',') }}"
        dest: "{{ csv_file }}"

    - name: Add one line per host
      include_tasks: ./ansible.collect.line.yml
      vars:
        hostname: "{{ item }}"
      loop: "{{ play_hosts }}"
      when: is_link == "false"

