#
# @copyright   Copyright (C) 2023 Combodo SARL
# @license     http://opensource.org/licenses/AGPL-3.0
#
# This task adds a line to the csv file being build for the current collection.
#
# Input parameters:
#  - hostname: Host to consider. The file containing its facts has the same name.
#  - primary_key_values: List of Ansible attributes to use to build the primary key
#  - ansible_host_attributes: List of Ansible attributes to consider from host inventory
#  - csv_file: File where the relevant host attributes will be appended in a new line
#
# Output parameters:
#  - Line appended to the csv_file with host attributes extracted from Ansible
#
---
- name: Import file content into variable
  ansible.builtin.include_vars:
    file: "{{ raw_directory }}/{{ hostname }}"
    name: jsondata

- name: Get line
  block:
    - name: Get primary key
      ansible.builtin.set_fact:
        primary_key_values: "{{ primary_key_values + [jsondata | community.general.json_query(primary_query)] }}"
      loop: "{{ primary_key }}"
      loop_control:
        loop_var: primary_query
      vars:
        primary_key_values: []

    - name: Get host attributes
      ansible.builtin.set_fact:
        attribute_values: "{{ attribute_values + [jsondata | community.general.json_query(host_query)] }}"
      loop: "{{ host_attributes }}"
      loop_control:
        loop_var: host_query
      vars:
        attribute_values: []

    - name: Get default attributes
      ansible.builtin.set_fact:
        default_values: "{{ default_values + [default_query] }}"
      loop: "{{ default_attributes }}"
      loop_control:
        loop_var: default_query
      vars:
        default_values: []

    - name: Apppend result to output file with default values
      ansible.builtin.lineinfile:
        path: "{{ csv_file }}"
        line: "{{ primary_key_values | join('_') }},{{ attribute_values | join(',') }},{{ default_values | join(',') }}"
      when: default_values is defined

    - name: Apppend result to output file with no default values
      ansible.builtin.lineinfile:
        path: "{{ csv_file }}"
        line: "{{ primary_key_values | join('_') }},{{ attribute_values | join(',') }}"
      when: default_values is undefined

  when: (collect_condition | bool == true) or (collect_condition)
  rescue:
    - name: Print when collection is not met
      ansible.builtin.debug:
        msg: "Collect condition is not met for {{ host_attributes }}"
